name: Manual Docker Scout

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Image Name'
        required: true
        default: 'php:8.4.1-cli-alpine3.20'

permissions:
  contents: read
  security-events: write
  pull-requests: write
jobs:
  scan:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker Scout
      id: docker-scout
      uses: docker/scout-action@v1
      with:
        command: cves, recommendations
        image: ${{ github.event.inputs.image_name }}
        sarif-file: sarif.output.json
        summary: true
